import { useState, useEffect } from 'react';
import './WorkList.css';
import './MyReports.css';

const API_URL = 'http://localhost:3001/api';

export default function MyReports(){
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showViewModal, setShowViewModal] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const response = await fetch(`${API_URL}/reports`);
      const data = await response.json();
      setReports(data);
    } catch (error) {
      console.error('Error fetching reports:', error);
      setReports([]);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return '-';
    const date = new Date(dateString);
    return date.toLocaleDateString('tr-TR', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const viewReport = (report) => {
    const reportData = typeof report.report_data === 'string' 
      ? JSON.parse(report.report_data) 
      : report.report_data;
    setSelectedReport({ ...report, parsedData: reportData });
    setShowViewModal(true);
  };

  const downloadPdf = async (report) => {
    setGeneratingPdf(true);
    try {
      const { default: jsPDF } = await import('jspdf');
      
      const reportData = typeof report.report_data === 'string' 
        ? JSON.parse(report.report_data) 
        : report.report_data;

      const doc = new jsPDF();
      let y = 20;

      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Lung Nodule Analysis Report', 105, y, { align: 'center' });
      y += 15;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Report ID: ${report.report_id}`, 20, y);
      y += 6;
      doc.text(`Generated: ${formatDate(report.created_at)}`, 20, y);
      y += 6;
      doc.text(`Generated By: ${report.generated_by || '-'}`, 20, y);
      y += 12;

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Patient Information', 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Patient Name: ${report.patient_name || '-'}`, 25, y);
      y += 6;
      doc.text(`Patient ID: ${report.patient_id || '-'}`, 25, y);
      y += 6;
      doc.text(`Study Date: ${report.study_date || '-'}`, 25, y);
      y += 6;
      doc.text(`Study ID: ${report.study_id || '-'}`, 25, y);
      y += 12;

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Nodule Analysis Summary', 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Nodules Detected: ${report.nodule_count || 0}`, 25, y);
      y += 6;
      doc.text(`Nodules Included in Report: ${report.included_nodule_count || 0}`, 25, y);
      y += 12;

      if (reportData?.nodules && reportData.nodules.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Nodule Details', 20, y);
        y += 10;

        reportData.nodules.forEach((nodule, index) => {
          if (y > 260) {
            doc.addPage();
            y = 20;
          }

          doc.setFontSize(11);
          doc.setFont('helvetica', 'bold');
          doc.text(`Nodule #${nodule.id || index + 1}`, 25, y);
          y += 6;

          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          doc.text(`Location: ${nodule.location || '-'}`, 30, y);
          y += 5;
          doc.text(`Size: ${nodule.size || '-'} mm`, 30, y);
          y += 5;
          doc.text(`AI Risk Assessment: ${nodule.risk || '-'}`, 30, y);
          y += 5;
          if (nodule.doctorAssessment) {
            doc.text(`Doctor Assessment: ${nodule.doctorAssessment}`, 30, y);
            y += 5;
          }
          if (nodule.notes) {
            doc.text(`Notes: ${nodule.notes}`, 30, y);
            y += 5;
          }
          y += 5;
        });
      }

      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
        doc.text('AI-Supported Lung Nodule Detection System', 105, 295, { align: 'center' });
      }

      doc.save(`report_${report.report_id}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF: ' + error.message);
    } finally {
      setGeneratingPdf(false);
    }
  };

  const handleDeleteReport = async (reportId) => {
    if (!confirm('Are you sure you want to delete this report?')) return;
    
    try {
      const response = await fetch(`${API_URL}/reports/${reportId}`, {
        method: 'DELETE'
      });
      if (response.ok) {
        setReports(reports.filter(r => r.report_id !== reportId));
      }
    } catch (error) {
      console.error('Error deleting report:', error);
    }
  };

  const getRiskBadge = (risk) => {
    const riskColors = { high: '#e74c3c', medium: '#f39c12', low: '#27ae60' };
    return (
      <span style={{
        padding: '2px 8px',
        borderRadius: '4px',
        backgroundColor: riskColors[risk] || '#95a5a6',
        color: 'white',
        fontSize: '11px',
        fontWeight: 'bold',
        textTransform: 'capitalize'
      }}>
        {risk}
      </span>
    );
  };

  if (loading) {
    return (
      <div className="worklist">
        <div style={{ textAlign: 'center', padding: '40px' }}>Loading...</div>
      </div>
    );
  }

  return (
    <div className="worklist">
      <div className="worklist-header">
        <h2>My Reports</h2>
        <p>View and manage your generated reports</p>
      </div>

      <div className="dashboard-section">
        <div className="table-wrapper">
          <table className="worklist-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Patient</th>
                <th>Study Date</th>
                <th>Nodules</th>
                <th>Generated By</th>
                <th>Created At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.length === 0 ? (
                <tr>
                  <td colSpan="7" style={{ textAlign: 'center', padding: '40px' }}>
                    <div style={{ color: '#95a5a6' }}>
                      <span style={{ fontSize: '48px' }}></span>
                      <p>No reports found</p>
                      <p style={{ fontSize: '12px' }}>Generate reports from the Review page</p>
                    </div>
                  </td>
                </tr>
              ) : (
                reports.map(report => (
                  <tr key={report.report_id}>
                    <td><code style={{ fontSize: '11px' }}>{report.report_id}</code></td>
                    <td>
                      <strong>{report.patient_name || '-'}</strong>
                      <br />
                      <span style={{ fontSize: '11px', color: '#666' }}>{report.patient_id}</span>
                    </td>
                    <td>{report.study_date || '-'}</td>
                    <td>
                      <span style={{ fontWeight: 'bold' }}>{report.included_nodule_count}</span>
                      <span style={{ color: '#666' }}> / {report.nodule_count}</span>
                    </td>
                    <td>{report.generated_by || '-'}</td>
                    <td>{formatDate(report.created_at)}</td>
                    <td>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <button className="open-btn view-btn" onClick={() => viewReport(report)}>
                          View
                        </button>
                        <button 
                          className="open-btn pdf-btn" 
                          onClick={() => downloadPdf(report)}
                          disabled={generatingPdf}
                        >
                          {generatingPdf ? '...' : ''} PDF
                        </button>
                        <button className="open-btn delete-btn" onClick={() => handleDeleteReport(report.report_id)}>
                          X
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* View Report Modal */}
      {showViewModal && selectedReport && (
        <div className="modal-overlay" onClick={() => setShowViewModal(false)}>
          <div className="report-view-modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Report Details</h3>
              <button className="close-btn" onClick={() => setShowViewModal(false)}>×</button>
            </div>
            
            <div className="modal-body">
              <div className="report-section">
                <h4>Report Information</h4>
                <div className="info-grid">
                  <div className="info-item"><label>Report ID</label><span>{selectedReport.report_id}</span></div>
                  <div className="info-item"><label>Created</label><span>{formatDate(selectedReport.created_at)}</span></div>
                  <div className="info-item"><label>Generated By</label><span>{selectedReport.generated_by || '-'}</span></div>
                  <div className="info-item"><label>Status</label><span className="status-badge">{selectedReport.status}</span></div>
                </div>
              </div>

              <div className="report-section">
                <h4>Patient Information</h4>
                <div className="info-grid">
                  <div className="info-item"><label>Name</label><span>{selectedReport.patient_name || '-'}</span></div>
                  <div className="info-item"><label>Patient ID</label><span>{selectedReport.patient_id}</span></div>
                  <div className="info-item"><label>Study Date</label><span>{selectedReport.study_date || '-'}</span></div>
                  <div className="info-item"><label>Study ID</label><span>{selectedReport.study_id}</span></div>
                </div>
              </div>

              <div className="report-section">
                <h4>Analysis Summary</h4>
                <div className="summary-cards">
                  <div className="summary-card">
                    <span className="number">{selectedReport.nodule_count || 0}</span>
                    <span className="label">Total Nodules</span>
                  </div>
                  <div className="summary-card">
                    <span className="number">{selectedReport.included_nodule_count || 0}</span>
                    <span className="label">Included in Report</span>
                  </div>
                </div>
              </div>

              {selectedReport.parsedData?.nodules && selectedReport.parsedData.nodules.length > 0 && (
                <div className="report-section">
                  <h4>Nodule Details</h4>
                  <div className="nodules-list">
                    {selectedReport.parsedData.nodules.map((nodule, index) => (
                      <div key={nodule.id || index} className="nodule-card">
                        <div className="nodule-header">
                          <span className="nodule-id">Nodule #{nodule.id || index + 1}</span>
                          {getRiskBadge(nodule.risk)}
                        </div>
                        <div className="nodule-details">
                          <div><label>Location:</label> {nodule.location || '-'}</div>
                          <div><label>Size:</label> {nodule.size || '-'} mm</div>
                          {nodule.doctorAssessment && (
                            <div><label>Doctor Assessment:</label> 
                              <span className={`assessment-badge ${nodule.doctorAssessment}`}>
                                {nodule.doctorAssessment}
                              </span>
                            </div>
                          )}
                          {nodule.notes && <div><label>Notes:</label> {nodule.notes}</div>}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="modal-footer">
              <button className="cancel-btn" onClick={() => setShowViewModal(false)}>Close</button>
              <button className="generate-btn" onClick={() => downloadPdf(selectedReport)}>
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

